### ISSUE TITLE
Filter out duplicating links before processing

### ISSUE THREAD

**Issue by Ignisor** [Ignisor/music-share-bot#12]

**Comment by alexshavelev44** [comment]
@Ignisor what did you mean?

if user sent deezer link in output will be only youtube/spotify/etc but not deezer?

**Comment by Ignisor** [comment]
@alexshavelev44 

No. I meant filtering exact duplicates (2 same links to one song from one service). Just a simple check.

**Comment by alexshavelev44** [comment]
@Ignisor are u sure it's a good idea? it's a rather logic bug than execute. and logic bug should be detected by unittests

**Comment by Ignisor** [comment]
What do you mean? I don't see a problem in making `set` from the URLs, so there will be only unique values.
And unfortunately our small bot is not so good and don't have unittest 🙁. But we need it for sure.

**Comment by alexshavelev44** [comment]
making set from urls it's like 
`if instance(int, x):
      pass
  elif isinstance(str, x):
      pass`

user can't affect message will have 2 same provider links, so this case has to be caught by tests.

**Comment by Ignisor** [comment]
Sorry, but I still not really understand. Let me clarify what I meant.

If the user sends a message like that:
```
Bla bla bla
https://music.youtube.com/watch?v=2_ANCiQOEfw&feature=share
And also it's bla bla bla
https://music.youtube.com/watch?v=2_ANCiQOEfw&feature=share
```

The bot will take additional time to process each link separately. But we don't need to spend that time (Because Amazon will charge us for each second on lambda). Because the result still will be the same.

**Comment by alexshavelev44** [comment]
uh, misunderstood case you were spoken before.

**Comment by alexshavelev44** [comment]
seems case with 2 links don't even work
![image](https://user-images.githubusercontent.com/45029602/55061143-b20e6c80-507b-11e9-8587-b00bc1fce2e6.png)

**Comment by Ignisor** [comment]
Currently, there is a timeout for 3 seconds and it takes more time. I will make it 5 seconds.

**Comment by Ignisor** [comment]
![image](https://user-images.githubusercontent.com/22328453/55061506-98b9f000-507c-11e9-912f-38b72c8ef385.png)

The output is okay, but the same output can be achieved in less time

**Comment by alexshavelev44** [comment]
hm, responded with only one set of links to all messages
![image](https://user-images.githubusercontent.com/45029602/55061565-c2731700-507c-11e9-8ba6-954b9243dacb.png)

**Comment by Ignisor** [comment]
But we still need to add the check for exact duplicates in the `core.urls.UrlsExtractor`, probably in `get_urls`. So APIs will not be used at all in that case.

**Comment by Ignisor** [comment]
https://github.com/Ignisor/music-share-bot/pull/34
