### ISSUE TITLE
Add GooglePlayMusic to music providers

### ISSUE THREAD

**Issue by Ignisor** [Ignisor/music-share-bot#16]

**Comment by Ignisor** [comment]
Thanks @alexshavelev

**Comment by Ignisor** [comment]
```
Traceback (most recent call last):

File "/var/task/package/telegram/ext/dispatcher.py", line 333, in process_update
handler.handle_update(update, self, check, context)
File "/var/task/package/telegram/ext/handler.py", line 120, in handle_update
return self.callback(dispatcher.bot, update, **optional_args)
File "/var/task/interfaces/telegram.py", line 31, in _handle_message
response = process_message(text)
File "/var/task/core/__init__.py", line 15, in process_message
name = url.get_name()
File "/var/task/core/urls.py", line 27, in get_name
return self.provider.get_music_name(self.url)
File "/var/task/core/providers/google_music.py", line 24, in get_music_name
title = soup.find('div', class_='title fade-out').text
AttributeError: 'NoneType' object has no attribute 'text'
```

@alexshavelev

**Comment by Ignisor** [comment]
@alexshavelev44

**Comment by alexshavelev44** [comment]
which url have you sent?

**Comment by Ignisor** [comment]
`https://play.google.com/music/r/m/T6nvbpguba3hajm7akwzgj5plly?t=Despicable_-_grandson`

**Comment by alexshavelev44** [comment]
uh, it's 'radio link', not the song. will process this

**Comment by alexshavelev44** [comment]
https://github.com/Ignisor/music-share-bot/pull/32

**Comment by Ignisor** [comment]
`https://play.google.com/music/m/Tgu46j7s3shbbzz4ee5xoja2qne?t=Angst__Four_-_The_Toxic_Avenger`
I also don't see any output nor errors for that link

**Comment by alexshavelev44** [comment]
album page only visible for logged in users, that's why i can't get artist/title

**Comment by Ignisor** [comment]
![ADD6F281-D36E-44CC-8DF9-57AF59D783BA](https://user-images.githubusercontent.com/22328453/55218724-8fab5900-520b-11e9-8f7d-5f267ef2fdd4.jpeg)

That link opens okay in incognito tab

**Comment by alexshavelev44** [comment]
@Ignisor hm, when i get page via requests i have only this html. do you have any suggestions?

![image](https://user-images.githubusercontent.com/45029602/55222563-e8cbba80-5214-11e9-96b9-caf0f87310e9.png)

![image](https://user-images.githubusercontent.com/45029602/55222577-f123f580-5214-11e9-9296-fead9893bc41.png)

**Comment by alexshavelev44** [comment]
with fake headers the same thing 
![image](https://user-images.githubusercontent.com/45029602/55222700-3ba57200-5215-11e9-96b1-40ef1203a2be.png)

**Comment by Ignisor** [comment]
In the HTML there is `content` of the `meta` tag that has the name that we need.

**Comment by Ignisor** [comment]
![image](https://user-images.githubusercontent.com/22328453/55227468-3994e080-5220-11e9-9c6f-c2b76f05e861.png)

**Comment by Ignisor** [comment]
https://github.com/Ignisor/music-share-bot/pull/38
