### ISSUE TITLE
Add report mismatch/absence button

### ISSUE THREAD

**Issue by dmitrysus** [Ignisor/music-share-bot#22]

**Comment by alexshavelev44** [comment]
@dmitrysus explain more. button under 'links message'? what should do?

**Comment by dmitrysus** [comment]
@alexshavelev44 it should resend given message to us so we could investigate

**Comment by alexshavelev44** [comment]
@dmitrysus is it ok?
![image](https://user-images.githubusercontent.com/45029602/55078683-5a83f700-50a3-11e9-9ab1-4d3d73bc340a.png)

**Comment by Ignisor** [comment]
That cool @alexshavelev44. Thanks! Sorry, GitHub did not sent me any emails about your PR, I think it's better to mention me using @

**Comment by Ignisor** [comment]
https://github.com/Ignisor/music-share-bot/pull/34
